## Object-Oriented Programming (OOP)
**Object-Oriented Programming (OOP)** is a programming paradigm that organizes code around objects; which are instances of classes, rather than functions or logic. 

It emerged in the 1960s and 70s as software systems grew more complex and harder to maintain using procedural approaches. OOP was designed to make code more modular, reusable, and easier to reason about by mimicking how we naturally think about things in the real world, ie. grouping data and the functions that operate on that data together.

Instance Variables/attributes- 
* Attributes - 
* methods - 
* Class Variables
* Instance methods

Attributes are variables that belong to a certain object(instance of a class). They can store the data or properties of that object. In the case of a dataframe:
* df.columns - attribute storing column names
* df.index - attribute that stores the row index
* df.dtypes - stores data on the data types of each column

Methods are functions that are associated with a particular class:
- df.info()
* df.head()
* df.describe()
* df.sort_values()
* df.drop()
* df.isna()

Essentially attributes in the context of a dataframe describe the state and structure of the dataframe while the methods tell us what actions we can perform to the said dataframe/instance of the dataframe.

Instance - an instance is an individual occurrence of an object created from a class with its own set of data and state.

Instance method - these are methods that operate on an instance of a class. They can access and modify the attributes of that instance.

With these terms now out of the way, lets create our own class, instantiate it, and use methods from the
classes to change update the attributes of said instances.

Why is self important?
    


In [1]:
import this

The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!


In [2]:
print('Hello world!!')

Hello world!!


In [3]:
x = 'Hello '
y = 'world!!'

print(x + y)

Hello world!!


In [23]:
import pandas as pd


df = pd.read_csv('~/Desktop/dsf_pt13/Phase1/code_challenge/fifa.csv')

type(df)

pandas.core.frame.DataFrame

In [11]:
df.tail()

ID                Name  Age  \
18202  238813        J. Lundstram   19   
18203  243165  N. Christoffersson   19   
18204  241638           B. Worman   16   
18205  246268      D. Walker-Rice   17   
18206  246269           G. Nugent   16   

                                                Photo Nationality  \
18202  https://cdn.sofifa.org/players/4/19/238813.png     England   
18203  https://cdn.sofifa.org/players/4/19/243165.png      Sweden   
18204  https://cdn.sofifa.org/players/4/19/241638.png     England   
18205  https://cdn.sofifa.org/players/4/19/246268.png     England   
18206  https://cdn.sofifa.org/players/4/19/246269.png     England   

                                      Flag  Overall  Potential  \
18202  https://cdn.sofifa.org/flags/14.png       47         65   
18203  https://cdn.sofifa.org/flags/46.png       47         63   
18204  https://cdn.sofifa.org/flags/14.png       47         67   
18205  https://cdn.sofifa.org/flags/14.png       47         66   
18206  https://cdn.sofifa.org/flags/14.png       46         66   

                   Club                                       Club Logo  ...  \
18202   Crewe Alexandra    https://cdn.sofifa.org/teams/2/light/121.png  ...   
18203    Trelleborgs FF    https://cdn.sofifa.org/teams/2/light/703.png  ...   
18204  Cambridge United   https://cdn.sofifa.org/teams/2/light/1944.png  ...   
18205   Tranmere Rovers  https://cdn.sofifa.org/teams/2/light/15048.png  ...   
18206   Tranmere Rovers  https://cdn.sofifa.org/teams/2/light/15048.png  ...   

      Composure Marking  StandingTackle SlidingTackle  GKDiving  GKHandling  \
18202      45.0    40.0            48.0          47.0      10.0        13.0   
18203      42.0    22.0            15.0          19.0      10.0         9.0   
18204      41.0    32.0            13.0          11.0       6.0         5.0   
18205      46.0    20.0            25.0          27.0      14.0         6.0   
18206      43.0    40.0            43.0          50.0      10.0        15.0   

       GKKicking GKPositioning GKReflexes Release Clause  
18202        7.0           8.0        9.0       143000.0  
18203        9.0           5.0       12.0       113000.0  
18204       10.0           6.0       13.0       165000.0  
18205       14.0           8.0        9.0       143000.0  
18206        9.0          12.0        9.0       165000.0  

[5 rows x 88 columns]

In [ ]:
x = [1,2, 3, 4, 5, 6]

x.head()

AttributeError: 'list' object has no attribute 'head'

In [9]:
x = pd.Series(x)

type(x)

pandas.core.series.Series

In [10]:
x.head()

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [12]:
df.columns

Index(['ID', 'Name', 'Age', 'Photo', 'Nationality', 'Flag', 'Overall',
       'Potential', 'Club', 'Club Logo', 'Value', 'Wage', 'Special',
       'Preferred Foot', 'International Reputation', 'Weak Foot',
       'Skill Moves', 'Work Rate', 'Body Type', 'Real Face', 'Position',
       'Jersey Number', 'Joined', 'Loaned From', 'Contract Valid Until',
       'Height', 'Weight', 'LS', 'ST', 'RS', 'LW', 'LF', 'CF', 'RF', 'RW',
       'LAM', 'CAM', 'RAM', 'LM', 'LCM', 'CM', 'RCM', 'RM', 'LWB', 'LDM',
       'CDM', 'RDM', 'RWB', 'LB', 'LCB', 'CB', 'RCB', 'RB', 'Crossing',
       'Finishing', 'HeadingAccuracy', 'ShortPassing', 'Volleys', 'Dribbling',
       'Curve', 'FKAccuracy', 'LongPassing', 'BallControl', 'Acceleration',
       'SprintSpeed', 'Agility', 'Reactions', 'Balance', 'ShotPower',
       'Jumping', 'Stamina', 'Strength', 'LongShots', 'Aggression',
       'Interceptions', 'Positioning', 'Vision', 'Penalties', 'Composure',
       'Marking', 'StandingTackle', 'SlidingTackle', 'GKDiv

In [13]:
df.shape

(18207, 88)

In [14]:
df.dtypes

ID                  int64
Name               object
Age                 int64
Photo              object
Nationality        object
                   ...   
GKHandling        float64
GKKicking         float64
GKPositioning     float64
GKReflexes        float64
Release Clause    float64
Length: 88, dtype: object

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18207 entries, 0 to 18206
Data columns (total 88 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   ID                        18207 non-null  int64  
 1   Name                      18207 non-null  object 
 2   Age                       18207 non-null  int64  
 3   Photo                     18207 non-null  object 
 4   Nationality               18207 non-null  object 
 5   Flag                      18207 non-null  object 
 6   Overall                   18207 non-null  int64  
 7   Potential                 18207 non-null  int64  
 8   Club                      17966 non-null  object 
 9   Club Logo                 18207 non-null  object 
 10  Value                     18207 non-null  object 
 11  Wage                      18207 non-null  object 
 12  Special                   18207 non-null  int64  
 13  Preferred Foot            18159 non-null  object 
 14  Intern

In [21]:
"""
lists
strings
int
floats
"""
name = 'brian chacha'

# name.upper()
name.split()

['brian', 'chacha']

In [22]:
type(name)

str

In [23]:
name = 23

name.upper()

AttributeError: 'int' object has no attribute 'upper'

In [27]:
def small_student():
    pass

In [ ]:
class Student:
    pass

In [4]:
"""
1. save full names(first & last)
2. uppercase/capitalise the name
3. send a 'welcome-to-moringa' message
"""

fullname = None

def get_name():
    firstname = str(input('FirstName? '))
    lastname = str(input('LastName? '))
    combinedname = firstname + " " + lastname
    return combinedname


def capitalize():
    return fullname.upper()


def welcome():
    return f"{fullname} welcome to Moringa School!!"




In [5]:
fullname = get_name()

fullname

'brian chacha'

In [10]:
fullname = capitalize()

fullname

'BRIAN CHACHA'

In [11]:
# type(Student)
welcome()

'BRIAN CHACHA welcome to Moringa School!!'

In [1]:
fullname = None

def get_name():
    firstname = str(input('FirstName? '))
    lastname = str(input('LastName? '))
    combinedname = firstname + " " + lastname
    return combinedname


In [2]:
get_name()

'brian chacha'

In [7]:
fullname

'brian chacha'

In [3]:
combinedname

NameError: name 'combinedname' is not defined

In [ ]:
#parent class
class Student:
    def __init__(self, first_name, last_name):
        #attributes
        self.first_name = first_name
        self.last_name = last_name

    def capitalize(self):
        fullname = self.first_name + self.last_name
        # return f"{self.first_name.upper()} {self.last_name.upper()}"
        return fullname.upper()
    

    def welcome(self):
        return f"Dear {self.first_name.upper()} welcome to Moringa School!!"

In [ ]:
student1 = Student('BrIan', 'ChacHA') #first instance of the Student class
student2 = Student('Abdullahi', 'Hassan') #Second instance of the Student class
student3 = Student('Salma', 'Jediel') #Third instance of the Student class
student4 = Student('David', 'davID') #fourth instance of the Student class
student5 = Student('Raphael', 'Ndemo') #fifth instance of the Student class



In [53]:
student3.welcome()

'Dear SALMA welcome to Moringa School!!'

In [27]:
student5.welcome()

'Dear RAPHAEL welcome to Moringa School!!'

In [28]:
student2.last_name

'Hassan'

In [32]:
student3.last_name

'Jediel'

In [31]:
student3.capitalize()

'SALMA JEDIEL'

### Inheritance
Inheritance in Python (and OOP in general) allows a `class` (called a **child** or **subclass**) to inherit attributes and methods from another class (called a parent or superclass). This promotes code reuse, making it easier to build on existing functionality without rewriting code. It also helps organize code in a clear hierarchy, making programs more maintainable and scalable.

In [72]:
#child class ---> inherits from the Student class.


class MoringaStudent(Student):
    def course(self):
        day_enrolled = str(input("Which day of the week did you enroll? "))
        return f"Your course is Data Science, you enrolled on {day_enrolled}."


In [68]:
ongoing_student = MoringaStudent('Joshua', 'Trump')

In [61]:
ongoing_student.first_name

'Joshua'

In [62]:
ongoing_student.last_name

'Trump'

### Scikit-learn
* `Estimators` - these have **.fit()** method.
* `Transformers` - these have **.transform()** method.
* `Predictor` - these have **.predict()** method.
* `Model` - these have **.score()** method.


In [85]:
from sklearn.preprocessing import StandardScaler
import numpy as np
import pandas as pd

x = pd.DataFrame([10, 10099, 1000, 1000, 100000])
x1 = pd.DataFrame([100, 199, 1000, 1008, 100000])

#instantiate 
scaler = StandardScaler()

scaler.fit(x)


StandardScaler()

0
0      10
1   10099
2    1000
3    1000
4  100000

In [83]:
x_scaled = scaler.transform(x)

x_scaled

array([[-0.57521757],
       [-0.31627496],
       [-0.5498084 ],
       [-0.5498084 ],
       [ 1.99110933]])

In [87]:
scaler.fit(x1)

x1_scaled = scaler.transform(x1)

x1_scaled

array([[-0.5119641 ],
       [-0.50947485],
       [-0.48933463],
       [-0.48913347],
       [ 1.99990705]])

In [86]:
x1_scaled = scaler.transform(x1)

x1_scaled

array([[-0.57290765],
       [-0.57036673],
       [-0.5498084 ],
       [-0.54960307],
       [ 1.99110933]])

In [ ]:
from sklearn.linear_model import LinearRegression


#instantiate
lr = LinearRegression()

x_train = ...
y_train = ...

lr.fit(x_train, y_train) # y = mx + c

x_test = ...

y_preds = lr.predict(x_test)


In [75]:
from sklearn.preprocessing import MinMaxScaler, OneHotEncoder


ohe = OneHotEncoder()

ohe

OneHotEncoder()

In [ ]:
# ages - 
# 24  -- youngest
# 80 -- oldest


#mean age 44

In [ ]:
80 - 24   

56

In [ ]:
#salaries
# 12000
# 960000

#30000   0

960000 - 12000  #1

948000

In [ ]:
"""
salaries

(10 - 22421.8)/sd --------- x1

10099- 22421.8)  /sd --------- x2
1000- 22421.8)  /sd --------- x3
1000- 22421.8)   /sd --------- x4
100000- 22421.8)  /sd --------- x5
"""
# y = mx + c 

import numpy as np


x = np.array(10, 10099, 1000, 1000, 100000)

mu = (10 + 10099 + 1000 + 1000 + 100000)/5

mu


22421.8